export const REPORT_FIELDS_TITLE_UPDATE = 'REPORT_FIELDS_TITLE_UPDATE';
export const REPORT_FIELDS_SOURCE_UPDATE = 'REPORT_FIELDS_SOURCE_UPDATE';
export const REPORT_FIELDS_AUTHOR_UPDATE = 'REPORT_FIELDS_AUTHOR_UPDATE';
export const REPORT_FIELDS_CONTENT_UPDATE = 'REPORT_FIELDS_CONTENT_UPDATE';

//FOR CREATE REPORT MODULE
export const REPORT_CREATE_REQUEST = 'REPORT_CREATE_REQUEST';
export const REPORT_CREATE_SUCCESS = 'REPORT_CREATE_SUCCESS';
export const REPORT_CREATE_FAIL = 'REPORT_CREATE_FAIL';
export const REPORT_FIELDS_TITLE_CREATE = 'REPORT_FIELDS_TITLE_CREATE';
export const REPORT_FIELDS_SOURCE_CREATE = 'REPORT_FIELDS_SOURCE_CREATE';
export const REPORT_FIELDS_AUTHOR_CREATE = 'REPORT_FIELDS_AUTHOR_CREATE';
export const REPORT_FIELDS_DATE_CREATE = 'REPORT_FIELDS_DATE_CREATE';
export const REPORT_FIELDS_CONTENT_CREATE = 'REPORT_FIELDS_CONTENT_CREATE';
