export const REPORT_FIELDS_TITLE_UPDATE = 'REPORT_FIELDS_TITLE_UPDATE';
export const REPORT_FIELDS_SOURCE_UPDATE = 'REPORT_FIELDS_SOURCE_UPDATE';
export const REPORT_FIELDS_AUTHOR_UPDATE = 'REPORT_FIELDS_AUTHOR_UPDATE';
export const REPORT_FIELDS_CONTENT_UPDATE = 'REPORT_FIELDS_CONTENT_UPDATE';
export const REPORT_CREATE_REQUEST = 'REPORT_CREATE_REQUEST';
export const REPORT_CREATE_SUCCESS = 'REPORT_CREATE_SUCCESS';
export const REPORT_CREATE_FAIL = 'REPORT_CREATE_FAIL';
